- name: Start
  width: slim
  hide-desktop-navigation: false
  center-vertically: true
  columns:
    - size: full
      widgets:
        - type: search
          autofocus: true
          search-engine: duckduckgo
          bangs:
          - title: YouTube
            shortcut: "!yt"
            url: https://www.youtube.com/results?search_query={QUERY}
          - title: Google
            shortcut: "!g"
            url: https://www.google.com/search?q={QUERY}

        - type: bookmarks
          groups:
            - title: General
              links:
                - title: Gmail
                  url: https://mail.google.com/mail/u/0/
                - title: Discord
                  url: https://discord.com/channels/@me
                - title: WhatsApp
                  url: https://web.whatsapp.com/
            - title: Entertainment
              links:
                - title: YouTube
                  url: https://www.youtube.com/
                - title: Youtube Music
                  url: https://music.youtube.com/
                - title: Twitch
                  url: https://www.twitch.com/
            - title: Social
              links:
                - title: Reddit
                  url: https://www.reddit.com/
                - title: Twitter
                  url: https://twitter.com/

