include:
  - downloaders/compose.yaml
  - external/compose.yaml
  - servarr/compose.yaml
  - traefik3/compose.yaml

networks:
  default:
    driver: bridge
  traefik-proxy: # Traefik needs its own network. Apps that want to enable Traefik must use the network
    name: traefik-proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

secrets:
  oauth_secrets:
    file: $DOCKER_SECRETS/oauth_secrets
  cf_dns_api_token:
    file: $DOCKER_SECRETS/cf_dns_api_token

services:
  watchtower: # Keeps containers updated
    image: containrrr/watchtower
    command:
      - --cleanup=true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
