# services:
#   nzbget:
#     container_name: nzbget
#     image: lscr.io/linuxserver/nzbget:latest
#     ports:
#       - 6789:6789
#     environment:
#       - PUID=$PUID
#       - PGID=$PGID
#       - TZ=$TZ
#       - NZBGET_USER=$USERNAME #optional
#       - NZBGET_PASS=pass #optional
#     volumes:
#       - $DOCKER_DIR/nzbget:/config
#       - $USENET_DIR:$USENET_DIR
#     restart: unless-stopped
