services:
###
# nzbget: NZB client. Currently disabled since I'm not familiar with NZB.
###
  # nzbget:
  #   container_name: nzbget
  #   image: lscr.io/linuxserver/nzbget:latest
  #   ports:
  #     - 6789:6789
  #   environment:
  #     - PUID=$PUID
  #     - PGID=$PGID
  #     - TZ=$TZ
  #     - NZBGET_USER=$USERNAME #optional
  #     - NZBGET_PASS=pass #optional
  #   volumes:
  #     - $DOCKER_DIR/nzbget:/config
  #     - $USENET_DIR:$USENET_DIR
  #   restart: unless-stopped

###
# qBittorrent: Bittorrent client.
###
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - WEBUI_PORT=8090
      - TORRENTING_PORT=6881
    volumes:
      - $DOCKER_DIR/qbittorrent:/config
      - $TORRENT_DIR:$TORRENT_DIR
    ports:
      - 8090:8090
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
