server:
  proxied: true

  # Note: assets are cached by the browser, changes to the CSS file
  # will not be reflected until the browser cache is cleared (Ctrl+F5)
  # custom-css-file: /assets/user.css
theme:
  # This will be the default theme
  disable-picker: false
  presets:
    default-dark:
      background-color: 225 14 15
      primary-color: 157 47 65
      contrast-multiplier: 1.1
    default-light:
      light: true
      background-color: 220 23 95
      contrast-multiplier: 1.0
      primary-color: 220 91 54
      positive-color: 109 58 40
      negative-color: 347 87 44

branding:
  hide-footer: true

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  - $include: pages/start.yml
  - $include: pages/home.yml
