# Sonarr - Anime only instance
services:
  sonarr-tvshows:
    container_name: sonarr-tvshows
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8990:8989
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKER_DIR/sonarr-tvshows:/config
      - $DATA_DIR:$DATA_DIR
