services:
  huntarr:
    image: ghcr.io/plexguide/huntarr:latest
    container_name: huntarr
    restart: unless-stopped
    ports:
      - 9705:9705
    environment:
      - TZ=$TZ
    volumes:
      - $DOCKER_DIR/huntarr:/config
