# Setup fail2ban with this if using funnel
# https://filebrowser.org/deployment.html?h=log#filter-configuration
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - 88:80
    volumes:
      - $FILESERVER_DIR:/srv
      - $DOCKER_DIR/filebrowser/database:/database
      - $DOCKER_DIR/filebrowser/config:/config
