include:
  - bazarr/compose.yaml
  - cleanuparr/compose.yaml
  - huntarr/compose.yaml
  - prowlarr/compose.yaml
  - radarr/compose.yaml
  - radarr-anime/compose.yaml
  - recyclarr/compose.yaml
  - sonarr-anime/compose.yaml
  - sonarr-tv/compose.yaml
