services:
###
# Radarr: Movies
###
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKER_DIR/radarr:/config
      - $DATA_DIR:$DATA_DIR

###
# Sonarr: Anime only instance on port 8989
###
  sonarr-anime:
    container_name: sonarr-anime
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKER_DIR/sonarr-anime:/config
      - $DATA_DIR:$DATA_DIR

###
# Sonarr: TV Shows instance on port 8990
###
  sonarr-tvshows:
    container_name: sonarr-tvshows
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8990:8989
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKER_DIR/sonarr-tvshows:/config
      - $DATA_DIR:$DATA_DIR

###
# Bazarr: Subtitles for tvshows
# Note: Anime subs are hard to come by, easier to add a profile on Sonarr to grab subbed shows.
###
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 6768:6767
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKER_DIR/bazarr:/config
      - $MEDIA_DIR:$MEDIA_DIR

###
# Prowlarr: Indexer manager
###
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKER_DIR/prowlarr:/config
