# https://cleanuparr.github.io/Cleanuparr/docs/installation/detailed/#docker-compose-method
services:
  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:latest
    container_name: cleanuparr
    restart: unless-stopped
    ports:
      - "11011:11011"
    volumes:
      - $DOCKER_DIR/cleanuparr:/config
    environment:
      - PORT=11011
      - BASE_PATH=
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=022
      - TZ=$TZ
    # Health check configuration
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11011/health"]
      interval: 30s        # Check every 30 seconds
      timeout: 10s         # Allow up to 10 seconds for response
      start_period: 30s    # Wait 30 seconds before first check
      retries: 3           # Mark unhealthy after 3 consecutive failures

