[filebrowser]

enabled = true
port = 80
filter = filebrowser
logpath = /docker-data/containers/*/*.log
maxretry = 10
bantime = 10m
findtime = 10m
banaction = iptables-allports
banaction_allports = iptables-allports
